files:
  - source: /src/main/resources/assets/narutomod/lang/en_us.json
    translation: /src/main/resources/assets/narutomod/lang/%locale_with_underscore%.json
commit_message: "lang: new translations {fileName} ({languageName}) [skip ci]"
append_commit_message: false
