files:
  - source: /src/main/resources/assets/narutomod/lang/en_us.json
    translation: /src/main/resources/assets/narutomod/lang/%locale_with_underscore%.json
commit_message: "lang: translations from crowdin [ci skip]"
append_commit_message: false
