package sekwah.mods.narutomod.items.itemmodels.armor;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import sekwah.mods.narutomod.client.player.models.ModelNinjaBiped;

/**
 * BorutoKidArmor - HeroGamezFTW
 * Created using Tabula 6.0.0
 */
public class ModelBorutoKidArmor extends ModelNinjaBiped {

    public ModelRenderer UpperBody;
    public ModelRenderer UpperRightArm;
    public ModelRenderer UpperLeftArm;
    public ModelRenderer UpperLeftLeg;
    public ModelRenderer UpperRightLeg;
    public ModelRenderer LowerBody;
    public ModelRenderer BLogo1;
    public ModelRenderer BLogo2;
    public ModelRenderer BLogo3;
    public ModelRenderer BLogo4;
    public ModelRenderer BLogo5;
    public ModelRenderer BLogo6;
    public ModelRenderer BLogo7;
    public ModelRenderer BLogo8;
    public ModelRenderer Jacket1;
    public ModelRenderer Jacket3;
    public ModelRenderer Jacket5;
    public ModelRenderer Jacket7;
    public ModelRenderer Jacket9;
    public ModelRenderer Jacket2;
    public ModelRenderer Jacket4;
    public ModelRenderer Jacket6;
    public ModelRenderer Jacket8;
    public ModelRenderer Jacket10;
    public ModelRenderer LowerRightArm;
    public ModelRenderer ArmJacket1;
    public ModelRenderer ArmJacket2;
    public ModelRenderer ArmJacket3;
    public ModelRenderer ArmJacket4;
    public ModelRenderer ArmLine1;
    public ModelRenderer ArmLine3;
    public ModelRenderer ArmLine2;
    public ModelRenderer ArmJacket5;
    public ModelRenderer ArmJacket6;
    public ModelRenderer ArmJacket7;
    public ModelRenderer ArmJacket8;
    public ModelRenderer Pink1;
    public ModelRenderer Pink3;
    public ModelRenderer Pink2;
    public ModelRenderer Pink4;
    public ModelRenderer LowerLeftArm;
    public ModelRenderer ArmJacket1_1;
    public ModelRenderer ArmJacket2_1;
    public ModelRenderer ArmJacket3_1;
    public ModelRenderer ArmJacket4_1;
    public ModelRenderer ArmLine1_1;
    public ModelRenderer ArmLine3_1;
    public ModelRenderer ArmJacket5_1;
    public ModelRenderer ArmJacket6_1;
    public ModelRenderer ArmJacket8_1;
    public ModelRenderer ArmJacket7_1;
    public ModelRenderer ArmLine2_1;
    public ModelRenderer Pink1_1;
    public ModelRenderer Pink2_1;
    public ModelRenderer Pink3_1;
    public ModelRenderer Pink4_1;
    public ModelRenderer LowerLeftLeg;
    public ModelRenderer Shoe1;
    public ModelRenderer Shoe2;
    public ModelRenderer Shoe3;
    public ModelRenderer Leg1;
    public ModelRenderer Leg3;
    public ModelRenderer Leg2;
    public ModelRenderer Leg4;
    public ModelRenderer LowerRightLeg;
    public ModelRenderer WhiteStrap3;
    public ModelRenderer WhiteStrap1;
    public ModelRenderer WhiteStrap4;
    public ModelRenderer WhiteStrap2;
    public ModelRenderer KunaiBag;
    public ModelRenderer KunaiBagStrap1;
    public ModelRenderer KunaiBagStrap3;
    public ModelRenderer KunaiBagStrap4;
    public ModelRenderer KunaiBagStrap2;
    public ModelRenderer Shoe1_1;
    public ModelRenderer Shoe2_1;
    public ModelRenderer Shoe3_1;
    public ModelRenderer Leg1_1;
    public ModelRenderer Leg2_1;
    public ModelRenderer Leg3_1;
    public ModelRenderer Leg4_1;

    public ModelBorutoKidArmor() {
        float expandValue = 0.001f;
        
        this.textureWidth = 150;
        this.textureHeight = 100;
        this.Leg4_1 = new ModelRenderer(this, 0, 56);
        this.Leg4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg4_1.addBox(-4.98F, -5.4F, -2.01F, 1, 1, 4, expandValue);
        this.Leg2_1 = new ModelRenderer(this, 0, 56);
        this.Leg2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg2_1.addBox(-7.98F, -5.4F, 1.02F, 4, 1, 1, expandValue);
        this.Jacket7 = new ModelRenderer(this, 70, 30);
        this.Jacket7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket7.addBox(2.0F, 0.01F, -2.06F, 2, 6, 1, expandValue);
        this.BLogo7 = new ModelRenderer(this, 50, 60);
        this.BLogo7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo7.addBox(-3.78F, 1.86F, -2.2F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo7, 0.0F, 0.8726646259971648F, -0.8726646259971648F);
        this.ArmJacket8 = new ModelRenderer(this, 100, 50);
        this.ArmJacket8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket8.addBox(5.04F, 2.01F, -2.03F, 1, 4, 4, expandValue);
        this.ArmJacket3_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket3_1.addBox(-1.03F, -1.99F, 1.04F, 4, 6, 1, expandValue);
        this.Pink3_1 = new ModelRenderer(this, 0, 56);
        this.Pink3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink3_1.addBox(-2.91F, 5.05F, -1.95F, 1, 1, 4, expandValue);
        this.ArmJacket2_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket2_1.addBox(2.04F, -1.99F, -1.97F, 1, 6, 4, expandValue);
        this.ArmJacket5_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket5_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket5_1.addBox(-5.97F, 2.01F, -2.04F, 4, 4, 1, expandValue);
        this.ArmJacket3 = new ModelRenderer(this, 100, 50);
        this.ArmJacket3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket3.addBox(-2.97F, -1.99F, 1.04F, 4, 6, 1, expandValue);
        this.BLogo4 = new ModelRenderer(this, 50, 60);
        this.BLogo4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo4.addBox(-0.73F, 2.3F, 1.1F, 1, 1, 1, expandValue);
        this.ArmJacket1_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket1_1.addBox(-0.97F, -1.99F, -2.04F, 4, 6, 1, expandValue);
        this.BLogo3 = new ModelRenderer(this, 50, 60);
        this.BLogo3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo3.addBox(-0.2F, 2.3F, 1.1F, 1, 1, 1, expandValue);
        this.UpperRightArm = new ModelRenderer(this, 40, 16);
        this.UpperRightArm.addBox(-3.0F, -2.0F, -2.0F, 4, 6, 4, expandValue);
        this.Jacket6 = new ModelRenderer(this, 70, 40);
        this.Jacket6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket6.addBox(-4.0F, 6.01F, -2.04F, 2, 6, 1, expandValue);
        this.Leg2 = new ModelRenderer(this, 0, 56);
        this.Leg2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg2.addBox(-3.99F, -5.4F, 1.02F, 4, 1, 1, expandValue);
        this.ArmJacket6_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket6_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket6_1.addBox(-2.96F, 2.01F, -1.97F, 1, 4, 4, expandValue);
        this.LowerLeftLeg = new ModelRenderer(this, 0, 28);
        this.LowerLeftLeg.addBox(-4.0F, -6.0F, -2.0F, 4, 6, 4, expandValue);
        this.UpperLeftArm = new ModelRenderer(this, 40, 16);
        this.UpperLeftArm.addBox(-1.0F, -2.0F, -2.0F, 4, 6, 4, expandValue);
        this.LowerBody = new ModelRenderer(this, 16, 28);
        this.LowerBody.addBox(-4.0F, 6.0F, -2.0F, 8, 6, 4, expandValue);
        this.ArmJacket5 = new ModelRenderer(this, 100, 50);
        this.ArmJacket5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket5.addBox(1.97F, 2.01F, -2.04F, 4, 4, 1, expandValue);
        this.BLogo2 = new ModelRenderer(this, 50, 60);
        this.BLogo2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo2.addBox(-2.25F, 1.1F, 1.1F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo2, 0.0F, 0.0F, -0.8726646259971648F);
        this.ArmJacket7 = new ModelRenderer(this, 100, 50);
        this.ArmJacket7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket7.addBox(2.03F, 2.01F, 1.04F, 4, 4, 1, expandValue);
        this.LowerRightLeg = new ModelRenderer(this, 0, 28);
        this.LowerRightLeg.addBox(-8.0F, -6.0F, -2.0F, 4, 6, 4, expandValue);
        this.ArmJacket2 = new ModelRenderer(this, 100, 50);
        this.ArmJacket2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket2.addBox(-3.04F, -1.99F, -1.97F, 1, 6, 4, expandValue);
        this.WhiteStrap2 = new ModelRenderer(this, 0, 80);
        this.WhiteStrap2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WhiteStrap2.addBox(-2.98F, 2.2F, -1.98F, 1, 2, 4, expandValue);
        this.ArmJacket7_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket7_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket7_1.addBox(-6.03F, 2.01F, 1.04F, 4, 4, 1, expandValue);
        this.KunaiBagStrap3 = new ModelRenderer(this, 20, 60);
        this.KunaiBagStrap3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.KunaiBagStrap3.addBox(-5.9F, 2.6F, -2.1F, 4, 1, 1, expandValue);
        this.WhiteStrap4 = new ModelRenderer(this, 0, 80);
        this.WhiteStrap4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WhiteStrap4.addBox(-6.01F, 2.2F, 1.02F, 4, 2, 1, expandValue);
        this.Leg3_1 = new ModelRenderer(this, 0, 56);
        this.Leg3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg3_1.addBox(-8.02F, -5.4F, -1.99F, 1, 1, 4, expandValue);
        this.UpperLeftLeg = new ModelRenderer(this, 0, 16);
        this.UpperLeftLeg.mirror = true;
        this.UpperLeftLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 6, 4, expandValue);
        this.Pink2 = new ModelRenderer(this, 0, 56);
        this.Pink2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink2.addBox(1.91F, 5.05F, 1.06F, 4, 1, 1, expandValue);
        this.Jacket5 = new ModelRenderer(this, 70, 30);
        this.Jacket5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket5.addBox(-4.0F, 0.01F, -2.06F, 2, 6, 1, expandValue);
        this.Pink2_1 = new ModelRenderer(this, 0, 56);
        this.Pink2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink2_1.addBox(-6.11F, 5.05F, 1.06F, 4, 1, 1, expandValue);
        this.Shoe1 = new ModelRenderer(this, 0, 43);
        this.Shoe1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe1.addBox(-4.0F, -1.0F, -3.0F, 4, 1, 1, expandValue);
        this.Jacket4 = new ModelRenderer(this, 70, 50);
        this.Jacket4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket4.addBox(-4.02F, 6.01F, -2.0F, 1, 6, 4, expandValue);
        this.ArmLine1 = new ModelRenderer(this, 100, 66);
        this.ArmLine1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine1.addBox(-3.06F, -2.06F, -0.5F, 1, 6, 1, expandValue);
        this.UpperBody = new ModelRenderer(this, 16, 16);
        this.UpperBody.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.UpperBody.addBox(-4.0F, 0.0F, -2.0F, 8, 6, 4, expandValue);
        this.Jacket1 = new ModelRenderer(this, 70, 20);
        this.Jacket1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket1.addBox(-4.0F, 0.01F, 1.04F, 8, 6, 1, expandValue);
        this.ArmJacket8_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket8_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket8_1.addBox(-6.04F, 2.01F, -2.03F, 1, 4, 4, expandValue);
        this.WhiteStrap1 = new ModelRenderer(this, 0, 80);
        this.WhiteStrap1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WhiteStrap1.addBox(-6.02F, 2.2F, -2.01F, 1, 2, 4, expandValue);
        this.Leg1_1 = new ModelRenderer(this, 0, 56);
        this.Leg1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg1_1.addBox(-8.01F, -5.4F, -2.02F, 4, 1, 1, expandValue);
        this.Pink1 = new ModelRenderer(this, 0, 56);
        this.Pink1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink1.addBox(2.11F, 5.05F, -2.06F, 4, 1, 1, expandValue);
        this.KunaiBagStrap4 = new ModelRenderer(this, 20, 60);
        this.KunaiBagStrap4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.KunaiBagStrap4.addBox(-6.1F, 2.6F, 1.1F, 4, 1, 1, expandValue);
        this.Jacket8 = new ModelRenderer(this, 70, 40);
        this.Jacket8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket8.addBox(2.0F, 6.01F, -2.04F, 2, 6, 1, expandValue);
        this.Shoe3_1 = new ModelRenderer(this, 0, 43);
        this.Shoe3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe3_1.addBox(-5.01F, -1.1F, -2.9F, 1, 2, 1, expandValue);
        this.setRotateAngle(Shoe3_1, -0.5235987755982988F, 0.0F, 0.0F);
        this.ArmLine2_1 = new ModelRenderer(this, 100, 66);
        this.ArmLine2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine2_1.addBox(-2.94F, 1.94F, -0.5F, 1, 4, 1, expandValue);
        this.Pink4_1 = new ModelRenderer(this, 0, 56);
        this.Pink4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink4_1.addBox(-6.11F, 5.05F, -2.05F, 1, 1, 4, expandValue);
        this.Shoe2_1 = new ModelRenderer(this, 0, 43);
        this.Shoe2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe2_1.addBox(-7.99F, -1.1F, -2.9F, 1, 2, 1, expandValue);
        this.setRotateAngle(Shoe2_1, -0.5235987755982988F, 0.0F, 0.0F);
        this.BLogo5 = new ModelRenderer(this, 50, 60);
        this.BLogo5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo5.addBox(2.04F, 1.51F, 1.1F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo5, 0.0F, 0.0F, 0.8726646259971648F);
        this.Jacket2 = new ModelRenderer(this, 70, 70);
        this.Jacket2.mirror = true;
        this.Jacket2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket2.addBox(-4.0F, 6.01F, 1.04F, 8, 6, 1, expandValue);
        this.Leg1 = new ModelRenderer(this, 0, 56);
        this.Leg1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg1.addBox(-4.01F, -5.4F, -2.02F, 4, 1, 1, expandValue);
        this.KunaiBagStrap1 = new ModelRenderer(this, 20, 60);
        this.KunaiBagStrap1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.KunaiBagStrap1.addBox(-6.1F, 2.6F, -2.1F, 1, 1, 4, expandValue);
        this.Jacket3 = new ModelRenderer(this, 70, 20);
        this.Jacket3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket3.addBox(-4.02F, 0.01F, -2.0F, 1, 6, 4, expandValue);
        this.WhiteStrap3 = new ModelRenderer(this, 0, 80);
        this.WhiteStrap3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WhiteStrap3.addBox(-5.98F, 2.2F, -2.02F, 4, 2, 1, expandValue);
        this.UpperRightLeg = new ModelRenderer(this, 0, 16);
        this.UpperRightLeg.addBox(-6.0F, 0.0F, -2.0F, 4, 6, 4, expandValue);
        this.Jacket10 = new ModelRenderer(this, 70, 50);
        this.Jacket10.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket10.addBox(3.02F, 6.01F, -2.0F, 1, 6, 4, expandValue);
        this.Shoe1_1 = new ModelRenderer(this, 0, 43);
        this.Shoe1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe1_1.addBox(-8.0F, -1.0F, -3.0F, 4, 1, 1, expandValue);
        this.Shoe2 = new ModelRenderer(this, 0, 43);
        this.Shoe2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe2.addBox(-3.99F, -1.1F, -2.9F, 1, 2, 1, expandValue);
        this.setRotateAngle(Shoe2, -0.5235987755982988F, 0.0F, 0.0F);
        this.LowerLeftArm = new ModelRenderer(this, 40, 28);
        this.LowerLeftArm.addBox(-6.0F, 2.0F, -2.0F, 4, 6, 4, expandValue);
        this.BLogo1 = new ModelRenderer(this, 50, 60);
        this.BLogo1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo1.addBox(1.3F, 1.04F, 1.1F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo1, 0.0F, 0.0F, 0.8726646259971648F);
        this.Pink4 = new ModelRenderer(this, 0, 56);
        this.Pink4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink4.addBox(5.11F, 5.05F, -1.95F, 1, 1, 4, expandValue);
        this.Jacket9 = new ModelRenderer(this, 70, 20);
        this.Jacket9.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Jacket9.addBox(3.02F, 0.01F, -2.0F, 1, 6, 4, expandValue);
        this.LowerRightArm = new ModelRenderer(this, 40, 28);
        this.LowerRightArm.addBox(2.0F, 2.0F, -2.0F, 4, 6, 4, expandValue);
        this.ArmLine3_1 = new ModelRenderer(this, 100, 66);
        this.ArmLine3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine3_1.addBox(-1.05F, -2.06F, -0.5F, 4, 1, 1, expandValue);
        this.ArmJacket4_1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket4_1.addBox(-1.04F, -1.99F, -2.03F, 1, 6, 4, expandValue);
        this.BLogo6 = new ModelRenderer(this, 50, 60);
        this.BLogo6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo6.addBox(-3.0F, 1.56F, 1.1F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo6, 0.0F, 0.0F, -0.8726646259971648F);
        this.ArmJacket4 = new ModelRenderer(this, 100, 50);
        this.ArmJacket4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket4.addBox(0.04F, -1.99F, -2.03F, 1, 6, 4, expandValue);
        this.ArmLine3 = new ModelRenderer(this, 100, 66);
        this.ArmLine3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine3.addBox(-3.05F, -2.06F, -0.5F, 4, 1, 1, expandValue);
        this.ArmJacket6 = new ModelRenderer(this, 100, 50);
        this.ArmJacket6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket6.addBox(1.96F, 2.01F, -1.97F, 1, 4, 4, expandValue);
        this.Leg3 = new ModelRenderer(this, 0, 56);
        this.Leg3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg3.addBox(-0.98F, -5.4F, -1.99F, 1, 1, 4, expandValue);
        this.Leg4 = new ModelRenderer(this, 0, 56);
        this.Leg4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Leg4.addBox(-4.02F, -5.4F, -2.01F, 1, 1, 4, expandValue);
        this.KunaiBag = new ModelRenderer(this, 20, 50);
        this.KunaiBag.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.KunaiBag.addBox(-6.6F, 1.9F, -0.5F, 1, 3, 1, expandValue);
        this.ArmLine2 = new ModelRenderer(this, 100, 66);
        this.ArmLine2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine2.addBox(1.94F, 1.94F, -0.5F, 1, 4, 1, expandValue);
        this.Pink3 = new ModelRenderer(this, 0, 56);
        this.Pink3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink3.addBox(1.91F, 5.05F, -2.05F, 1, 1, 4, expandValue);
        this.KunaiBagStrap2 = new ModelRenderer(this, 20, 60);
        this.KunaiBagStrap2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.KunaiBagStrap2.addBox(-2.9F, 2.6F, -1.9F, 1, 1, 4, expandValue);
        this.ArmLine1_1 = new ModelRenderer(this, 100, 66);
        this.ArmLine1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmLine1_1.addBox(2.06F, -2.06F, -0.5F, 1, 6, 1, expandValue);
        this.Shoe3 = new ModelRenderer(this, 0, 43);
        this.Shoe3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Shoe3.addBox(-1.01F, -1.1F, -2.9F, 1, 2, 1, expandValue);
        this.setRotateAngle(Shoe3, -0.5235987755982988F, 0.0F, 0.0F);
        this.Pink1_1 = new ModelRenderer(this, 0, 56);
        this.Pink1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Pink1_1.addBox(-5.91F, 5.05F, -2.06F, 4, 1, 1, expandValue);
        this.BLogo8 = new ModelRenderer(this, 50, 60);
        this.BLogo8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BLogo8.addBox(2.78F, 1.86F, -2.2F, 1, 1, 1, expandValue);
        this.setRotateAngle(BLogo8, 0.0F, -0.8726646259971648F, 0.8726646259971648F);
        this.ArmJacket1 = new ModelRenderer(this, 100, 50);
        this.ArmJacket1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ArmJacket1.addBox(-3.03F, -1.99F, -2.04F, 4, 6, 1, expandValue);
        this.LowerRightLeg.addChild(this.Leg4_1);
        this.LowerRightLeg.addChild(this.Leg2_1);
        this.UpperBody.addChild(this.Jacket7);
        this.UpperBody.addChild(this.BLogo7);
        this.LowerRightArm.addChild(this.ArmJacket8);
        this.UpperLeftArm.addChild(this.ArmJacket3_1);
        this.LowerLeftArm.addChild(this.Pink3_1);
        this.UpperLeftArm.addChild(this.ArmJacket2_1);
        this.LowerLeftArm.addChild(this.ArmJacket5_1);
        this.UpperRightArm.addChild(this.ArmJacket3);
        this.UpperBody.addChild(this.BLogo4);
        this.UpperLeftArm.addChild(this.ArmJacket1_1);
        this.UpperBody.addChild(this.BLogo3);
        this.LowerBody.addChild(this.Jacket6);
        this.LowerLeftLeg.addChild(this.Leg2);
        this.LowerLeftArm.addChild(this.ArmJacket6_1);
        this.LowerRightArm.addChild(this.ArmJacket5);
        this.UpperBody.addChild(this.BLogo2);
        this.LowerRightArm.addChild(this.ArmJacket7);
        this.UpperRightArm.addChild(this.ArmJacket2);
        this.UpperRightLeg.addChild(this.WhiteStrap2);
        this.LowerLeftArm.addChild(this.ArmJacket7_1);
        this.UpperRightLeg.addChild(this.KunaiBagStrap3);
        this.UpperRightLeg.addChild(this.WhiteStrap4);
        this.LowerRightLeg.addChild(this.Leg3_1);
        this.LowerRightArm.addChild(this.Pink2);
        this.UpperBody.addChild(this.Jacket5);
        this.LowerLeftArm.addChild(this.Pink2_1);
        this.LowerLeftLeg.addChild(this.Shoe1);
        this.LowerBody.addChild(this.Jacket4);
        this.UpperRightArm.addChild(this.ArmLine1);
        this.UpperBody.addChild(this.Jacket1);
        this.LowerLeftArm.addChild(this.ArmJacket8_1);
        this.UpperRightLeg.addChild(this.WhiteStrap1);
        this.LowerRightLeg.addChild(this.Leg1_1);
        this.LowerRightArm.addChild(this.Pink1);
        this.UpperRightLeg.addChild(this.KunaiBagStrap4);
        this.LowerBody.addChild(this.Jacket8);
        this.LowerRightLeg.addChild(this.Shoe3_1);
        this.LowerLeftArm.addChild(this.ArmLine2_1);
        this.LowerLeftArm.addChild(this.Pink4_1);
        this.LowerRightLeg.addChild(this.Shoe2_1);
        this.UpperBody.addChild(this.BLogo5);
        this.LowerBody.addChild(this.Jacket2);
        this.LowerLeftLeg.addChild(this.Leg1);
        this.UpperRightLeg.addChild(this.KunaiBagStrap1);
        this.UpperBody.addChild(this.Jacket3);
        this.UpperRightLeg.addChild(this.WhiteStrap3);
        this.LowerBody.addChild(this.Jacket10);
        this.LowerRightLeg.addChild(this.Shoe1_1);
        this.LowerLeftLeg.addChild(this.Shoe2);
        this.UpperBody.addChild(this.BLogo1);
        this.LowerRightArm.addChild(this.Pink4);
        this.UpperBody.addChild(this.Jacket9);
        this.UpperLeftArm.addChild(this.ArmLine3_1);
        this.UpperLeftArm.addChild(this.ArmJacket4_1);
        this.UpperBody.addChild(this.BLogo6);
        this.UpperRightArm.addChild(this.ArmJacket4);
        this.UpperRightArm.addChild(this.ArmLine3);
        this.LowerRightArm.addChild(this.ArmJacket6);
        this.LowerLeftLeg.addChild(this.Leg3);
        this.LowerLeftLeg.addChild(this.Leg4);
        this.UpperRightLeg.addChild(this.KunaiBag);
        this.LowerRightArm.addChild(this.ArmLine2);
        this.LowerRightArm.addChild(this.Pink3);
        this.UpperRightLeg.addChild(this.KunaiBagStrap2);
        this.UpperLeftArm.addChild(this.ArmLine1_1);
        this.LowerLeftLeg.addChild(this.Shoe3);
        this.LowerLeftArm.addChild(this.Pink1_1);
        this.UpperBody.addChild(this.BLogo8);
        this.UpperRightArm.addChild(this.ArmJacket1);

        this.LowerBody.setRotationPoint(0.0F, -6.0F, 0.0F);
        this.UpperLeftArm.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LowerLeftArm.setRotationPoint(4.0F, -2.0F, 0.0F);
        this.UpperRightArm.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LowerRightArm.setRotationPoint(-4.0F, -2.0F, 0.0F);

        this.UpperLeftLeg.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LowerLeftLeg.setRotationPoint(2.0F, 6.0F, 0.0F);
        this.UpperRightLeg.setRotationPoint(4.0F, 0.0F, 0.0F);
        this.LowerRightLeg.setRotationPoint(6.0F, 6.0F, 0.0F);

    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        this.renderTracked(this.UpperLeftArm, f5, this.bipedLeftArmUpper);
        this.renderTracked(this.LowerLeftArm, f5, this.bipedLeftArmUpper, this.bipedLeftArmLower);
        this.renderTracked(this.UpperRightArm, f5, this.bipedRightArmUpper);
        this.renderTracked(this.LowerRightArm, f5, this.bipedRightArmUpper, this.bipedRightArmLower);
        this.renderTracked(this.UpperLeftLeg, f5, this.bipedLeftLegUpper);
        this.renderTracked(this.LowerLeftLeg, f5, this.bipedLeftLegUpper, this.bipedLeftLegLower);
        this.renderTracked(this.UpperRightLeg, f5, this.bipedRightLegUpper);
        this.renderTracked(this.LowerRightLeg, f5, this.bipedRightLegUpper, this.bipedRightLegLower);
        this.renderTracked(this.UpperBody, f5, this.bipedBody);
        this.renderTracked(this.LowerBody, f5, this.bipedLowerBody);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
