name: Build Project

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Download MC assets
        run: ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
      - name: Run DataGen
        run: './gradlew runData'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to Discord (If pre-release tag)
        if: "startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-')"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: ./gradlew discordupload
      - name: Publish to Curseforge (If release tag)
        if: "startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')"
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
        run: ./gradlew curseforge
      - name: Upload Forge Version file
        if: "startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 cp ./docs/forgeupdatefile s3://${{secrets.AWS_BUCKET}}/modversions/ --recursive
