
on:
  workflow_dispatch:
name: "Manual Release (emergency fix)"
jobs:
  # This  is for when forge doesn't work or something screws up
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Download MC assets
        run: ./gradlew downloadAssets --debug || ./gradlew downloadAssets --debug || (sleep 30s && ./gradlew downloadAssets --debug)
      - name: Run DataGen
        run: ./gradlew runData
      - name: Build and publish (release)
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          IS_RELEASE: true
        run: |
          # Build
          ./gradlew build discordupload curseforge
